#!/usr/bin/env bash
# configures an Nginx server to listen on port 80

# creates a symbolic link (-s option) btw the Nginx configurtion file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
